### ISSUE TITLE
Opdracht uitleg maandag 24-04

### ISSUE THREAD

**Issue by CathelijneVisser** [CathelijneVisser/performance-matters-optimized-website#16]
![Image](https://user-images.githubusercontent.com/112859814/233938423-43b7ec4b-e6c9-465c-971b-1cc3ac75dac8.jpg)

https://www.smashingmagazine.com/2021/01/front-end-performance-2021-free-pdf-checklist/

**Comment by CelinexPutte** [comment]
Gedaan op 24-04
