### ISSUE TITLE
Living styleguide 'maken'

### ISSUE THREAD

**Issue by CelinexPutte** [CathelijneVisser/performance-matters-optimized-website#5]
- [x] Nieuwe repo maken 
- [x] Code kopiëren
- [ ] Aanpassen aan format
- [ ] Css maken
- [ ] Styleguide aanpassen

**Comment by CelinexPutte** [comment]
Nieuw plan:

In wiki maken, geen nieuwe website.

- [x] Afbeeldingen
- [x] Kleuren
- [x] Css opbouw
- [x] JS client opbouw
- [x] EJS opbouw
- [x] Node opbouw
- [x] Taal in code
- [x] Comments
- [ ] ...

**Comment by CathelijneVisser** [comment]
Af op 10-05
